// Automatically generated by astro-icon
// 68a175bc48fda7a3a671515e7456281aee10bdc6f4a7d5b6ed068d393f6374ce

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "icon-cinnamon"
		| "icon-close"
		| "icon-cubs"
		| "icon-fire-big"
		| "icon-fire-small"
		| "icon-hot-paper"
		| "icon-paper-small"
		| "icon-roll"
		| "icon-scorpio"
		| "logo";
}