// Automatically generated by astro-icon
// adbcdc630a2d2c72c8813203f89d82963e2c37d1912ce122a589a8fb8bac658e

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "icon-cinnamon"
		| "icon-cubs"
		| "icon-fire-big"
		| "icon-fire-small"
		| "icon-hot-paper"
		| "icon-paper-small"
		| "icon-roll"
		| "icon-scorpio"
		| "logo";
}